#################### default parameters ################################
logo = "images/ws-logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Kom Ig책ng"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "Denna sidan anv채nder kakor. Genom att anv채nda denna hemsida accepterar du dessa."
button = "Jag godk채nner"
  
############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "twitter"
#icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"